version: '3.8'

services:
  hypertube-express:
    image: hypertube-express-dev
    container_name: hypertube-express-dev
    depends_on: 
      - postgres
    env_file:
      - ./docker/postgres/.postgres-env
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - 80:3000
    volumes:
      - ./server:/app
      - /app/node_modules # anonymous volume (not bound to host)
