FROM node:18-alpine

RUN apk add --no-cache tzdata

ENV TZ='Europe/Helsinki'

WORKDIR /app

COPY ./server/package.json ./server/package-lock.json ./

RUN npm install --global nodemon npm@9.2.0 && npm install

EXPOSE 3000

CMD ["npm", "run", "dev"]